name: Build My Google Drive Extension

on:
  push:
    paths:
      - 'src/all/mygoogledrive/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew :src:all:mygoogledrive:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MyGoogleDrive-Anime-Extension
          path: src/all/mygoogledrive/build/outputs/apk/debug/*.apk

